"""Shared planning and MAVLink defaults."""

BATTERY_USABLE_FRACTION = 0.85
SOLVER_TIME_LIMIT_SECONDS = 5
DEFAULT_CRUISE_SPEED_MPS = 18.0
DEFAULT_MISSION_ALTITUDE_M = 120.0
DEFAULT_TRANSIT_ALTITUDE_M = 50.0
DEFAULT_MAVLINK_TIMEOUT_SECONDS = 10.0
DEFAULT_CAMERA_TRIGGER_DISTANCE_M = 1.0
TURN_TIME_SECONDS = 4
